### ISSUE TITLE
Consider removing hard dependency on owl

### ISSUE THREAD

**Issue by fhunleth** [kevinschweikert/mndp#9]
While I like `owl`, I think it's really nice when libraries like this have minimal dependencies. It comes in handy when working on projects where people scrutinize each dependency. Until you see how it's used here, it's a little surprising when a networking library pulls in a TUI library.

I have.a couple ideas that I wanted to run by you:

1. Make `:owl` an optional dependency. Users will get an error when running the TUI functions. This seems annoying, but not unexpected.
2. Break the TUI into another library. I don't know what your plans are for the TUI, but if you were thinking about extending it a lot, this might make sense regardless.
3. Rewrite the `:owl` parts. Erlang's IO formatting supports fixed width fields well. See https://www.erlang.org/doc/apps/stdlib/io.html#fwrite/3.

**Comment by kevinschweikert** [comment]
@fhunleth I started working on this in the linked PR
